apiVersion: apps/v1
kind: Deployment
metadata:
  name: wexa-ai-deployment
  labels:
    app: wexa-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wexa-ai
  template:
    metadata:
      labels:
        app: wexa-ai
    spec:
      containers:
        - name: wexa-ai-container
          image: ghcr.io/rajeshkurumoju/wexa-ai:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5

