name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4️⃣ Extract metadata (for tagging)
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/wexa-ai

      # 5️⃣ Build and push the Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/wexa-ai:latest
            ghcr.io/${{ github.repository_owner }}/wexa-ai:${{ github.run_number }}
            ghcr.io/${{ github.repository_owner }}/wexa-ai:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      # 6️⃣ Confirmation
      - name: Confirm push
        run: echo "✅ Docker image successfully pushed to GHCR!"

